/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from 'bn.js';
import { ContractOptions } from 'web3-eth-contract';
import { EventLog } from 'web3-core';
import { EventEmitter } from 'events';
import { Callback, PayableTransactionObject, NonPayableTransactionObject, BlockType, ContractEventLog, BaseContract } from './types';

export interface EventOptions {
    filter?: object;
    fromBlock?: BlockType;
    topics?: string[];
}

export type Approval = ContractEventLog<{
    owner: string;
    approved: string;
    tokenId: string;
    0: string;
    1: string;
    2: string;
}>;
export type ApprovalForAll = ContractEventLog<{
    owner: string;
    operator: string;
    approved: boolean;
    0: string;
    1: string;
    2: boolean;
}>;
export type MoleculeDecompositionStarted = ContractEventLog<{
    owner: string;
    tokenId: string;
    burnDate: string;
    0: string;
    1: string;
    2: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
    previousOwner: string;
    newOwner: string;
    0: string;
    1: string;
}>;
export type Transfer = ContractEventLog<{
    from: string;
    to: string;
    tokenId: string;
    0: string;
    1: string;
    2: string;
}>;

export interface XSublimatio extends BaseContract {
    constructor(jsonInterface: any[], address?: string, options?: ContractOptions): XSublimatio;
    clone(): XSublimatio;
    methods: {
        approve(to: string, tokenId: number | string | BN): NonPayableTransactionObject<void>;

        balanceOf(owner: string): NonPayableTransactionObject<string>;

        baseURI(): NonPayableTransactionObject<string>;

        brew(
            tokenIds_: (number | string | BN)[],
            drugType_: number | string | BN,
            destination_: string
        ): NonPayableTransactionObject<string>;

        burnDates(arg0: number | string | BN): NonPayableTransactionObject<string>;

        contractURI(): NonPayableTransactionObject<string>;

        decompose(tokenId_: number | string | BN): NonPayableTransactionObject<void>;

        drugsAvailable(): NonPayableTransactionObject<string>;

        getApproved(tokenId: number | string | BN): NonPayableTransactionObject<string>;

        getDrugAvailability(drugType_: number | string | BN): NonPayableTransactionObject<string>;

        getMoleculeAvailability(moleculeType_: number | string | BN): NonPayableTransactionObject<string>;

        getRecipe(drugType_: number | string | BN): NonPayableTransactionObject<string[]>;

        isApprovedForAll(owner: string, operator: string): NonPayableTransactionObject<boolean>;

        moleculesAvailable(): NonPayableTransactionObject<string>;

        name(): NonPayableTransactionObject<string>;

        owner(): NonPayableTransactionObject<string>;

        ownerOf(tokenId: number | string | BN): NonPayableTransactionObject<string>;

        purchase(destination_: string, minQuantity_: number | string | BN): PayableTransactionObject<string[]>;

        renounceOwnership(): NonPayableTransactionObject<void>;

        'safeTransferFrom(address,address,uint256)'(
            from: string,
            to: string,
            tokenId: number | string | BN
        ): NonPayableTransactionObject<void>;

        'safeTransferFrom(address,address,uint256,bytes)'(
            from: string,
            to: string,
            tokenId: number | string | BN,
            _data: string | number[]
        ): NonPayableTransactionObject<void>;

        setApprovalForAll(operator: string, approved: boolean): NonPayableTransactionObject<void>;

        startDecomposition(tokenId_: number | string | BN): NonPayableTransactionObject<void>;

        supportsInterface(interfaceId: string | number[]): NonPayableTransactionObject<boolean>;

        symbol(): NonPayableTransactionObject<string>;

        tokenByIndex(index: number | string | BN): NonPayableTransactionObject<string>;

        tokenOfOwnerByIndex(owner: string, index: number | string | BN): NonPayableTransactionObject<string>;

        tokenURI(tokenId: number | string | BN): NonPayableTransactionObject<string>;

        totalSupply(): NonPayableTransactionObject<string>;

        transferFrom(from: string, to: string, tokenId: number | string | BN): NonPayableTransactionObject<void>;

        transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

        withdrawProceeds(amount_: number | string | BN, destination_: string): NonPayableTransactionObject<void>;
    };
    events: {
        Approval(cb?: Callback<Approval>): EventEmitter;
        Approval(options?: EventOptions, cb?: Callback<Approval>): EventEmitter;

        ApprovalForAll(cb?: Callback<ApprovalForAll>): EventEmitter;
        ApprovalForAll(options?: EventOptions, cb?: Callback<ApprovalForAll>): EventEmitter;

        MoleculeDecompositionStarted(cb?: Callback<MoleculeDecompositionStarted>): EventEmitter;
        MoleculeDecompositionStarted(options?: EventOptions, cb?: Callback<MoleculeDecompositionStarted>): EventEmitter;

        OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
        OwnershipTransferred(options?: EventOptions, cb?: Callback<OwnershipTransferred>): EventEmitter;

        Transfer(cb?: Callback<Transfer>): EventEmitter;
        Transfer(options?: EventOptions, cb?: Callback<Transfer>): EventEmitter;

        allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
    };

    once(event: 'Approval', cb: Callback<Approval>): void;
    once(event: 'Approval', options: EventOptions, cb: Callback<Approval>): void;

    once(event: 'ApprovalForAll', cb: Callback<ApprovalForAll>): void;
    once(event: 'ApprovalForAll', options: EventOptions, cb: Callback<ApprovalForAll>): void;

    once(event: 'MoleculeDecompositionStarted', cb: Callback<MoleculeDecompositionStarted>): void;
    once(event: 'MoleculeDecompositionStarted', options: EventOptions, cb: Callback<MoleculeDecompositionStarted>): void;

    once(event: 'OwnershipTransferred', cb: Callback<OwnershipTransferred>): void;
    once(event: 'OwnershipTransferred', options: EventOptions, cb: Callback<OwnershipTransferred>): void;

    once(event: 'Transfer', cb: Callback<Transfer>): void;
    once(event: 'Transfer', options: EventOptions, cb: Callback<Transfer>): void;
}
