/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { XSublimatio } from './XSublimatio';

export { XSublimatio__factory } from './factories/XSublimatio__factory';
